Repository bitcamp-aiaas-9/FilmNote, pull requests merged in 2024-09, with the labels that each got.

#18 fix : header logo, button
  src/main/webapp/common/header.jsp
  src/main/webapp/image/film_favicon.png
  src/main/webapp/image/filmnote_logo.png
Labels: Client

#20 Sql 추가
  .classpath
  build/classes/.gitignore
  src/main/java/main/IndexService.java
  src/main/java/main/dao/IndexDAO.java
  src/main/java/mapper/indexMapper.xml
  src/main/resources/sql/admin_tb.sql
  src/main/resources/sql/movie_tb.sql
  src/main/resources/sql/review_tb.sql
  src/main/resources/sql/user_tb.sql
  src/main/webapp/WEB-INF/lib/json-simple-1.1.1.jar
  src/main/webapp/WEB-INF/lib/mysql-connector-j-9.0.0.jar
  src/main/webapp/common/header.jsp
Labels: Server

#22 DTO, SQL 등 추가
  .project
  build/classes/.gitignore
  build/classes/db.properties
  build/classes/mybatis-config.xml
  src/main/java/db.properties
  src/main/java/movie/bean/MovieDTO.java
  src/main/java/mybatis-config.xml
  src/main/java/review/bean/ReviewDTO.java
  src/main/java/user/bean/MyBatisConnectionFactory.java
  src/main/java/user/bean/UserDTO.java
  src/main/java/user/dao/UserDAO.java
  src/main/java/user/service/userSignInDBService.java
  src/main/java/user/service/userSignInService.java
  src/main/java/user/service/userSignUpDBService.java
  src/main/java/user/service/userSignUpService.java
  src/main/webapp/common/header.jsp
  src/main/webapp/css/userSignIn.css
  src/main/webapp/css/userSignUp.css
  src/main/webapp/image/Reg.png
  src/main/webapp/js/userSignIn.js
  src/main/webapp/js/userSignUp.js
  src/main/webapp/user/userSignIn.jsp
  src/main/webapp/user/userSignUp.jsp
Labels: Server

#25 fix : 수많은 오류 및 서버 생성
  build/classes/.gitignore
  build/classes/db.properties
  build/classes/mapper/indexMapper.xml
  build/classes/mybatis-config.xml
  src/main/java/db.properties
  src/main/java/mybatis-config.xml
  src/main/java/review/service/ReviewViewDBService.java
  src/main/java/review/service/ReviewViewService.java
  src/main/java/user/service/UserSignInDBService.java
  src/main/java/user/service/UserSignInService.java
  src/main/java/user/service/UserSignUpDBService.java
  src/main/java/user/service/UserSignUpService.java
  src/main/java/user/service/userSignInService.java
  src/main/java/user/service/userSignUpService.java
  src/main/resources/sql/review_tb.sql
  src/main/webapp/WEB-INF/command.properties
  src/main/webapp/common/header.jsp
  src/main/webapp/css/init.css
  src/main/webapp/review/reviewView.jsp
Labels: documentation, Server

#27 movieBoard.jsp 완성
  build/classes/.gitignore
  build/classes/mapper/movieMapper.xml
  build/classes/mybatis-config.xml
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/bean/MovieDTO.java
  src/main/java/movie/bean/MoviePaging.java
  src/main/java/movie/dao/MovieDAO.java
  src/main/java/movie/service/MovieBoardService.java
  src/main/java/mybatis-config.xml
  src/main/webapp/admin/movieBoard.jsp
  src/main/webapp/admin/movieWrite.jsp
  src/main/webapp/common/adminMenu.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/css/init.css
  src/main/webapp/css/movieBoard.css
  src/main/webapp/js/movieBoard.js
  src/main/webapp/js/movieWrite.js
Labels: Server

#31 점심 풀리퀘
  build/classes/.gitignore
  build/classes/mapper/userMapper.xml
  src/main/java/mapper/userMapper.xml
  src/main/java/user/dao/UserDAO.java
  src/main/java/user/service/CheckIdService.java
  src/main/java/user/service/UserSignUpDBService.java
  src/main/java/user/service/UserSignUpService.java
  src/main/webapp/WEB-INF/command.properties
  src/main/webapp/css/userSignUp.css
  src/main/webapp/js/userSignUp.js
  src/main/webapp/user/userSignUp.jsp
Labels: Client

#32 Dev tw
  build/classes/mapper/userMapper.xml
  src/main/java/mapper/userMapper.xml
  src/main/java/user/dao/UserDAO.java
  src/main/java/user/service/UserEditDBService.java
  src/main/java/user/service/UserEditService.java
  src/main/java/user/service/UserWithdrawDBService.java
  src/main/java/user/service/UserWithdrawService.java
  src/main/webapp/common/header.jsp
  src/main/webapp/css/userEdit.css
  src/main/webapp/image/iu1.jpg
  src/main/webapp/js/userEdit.js
  src/main/webapp/js/userWithdraw.js
  src/main/webapp/user/userEdit.jsp
  src/main/webapp/user/userWithdraw.jsp
Labels: Client, Server

#35 Update userMapper.xml
  src/main/java/mapper/userMapper.xml
Labels: bug

#36 로그인,로그아웃 로직 수정
  build/classes/mapper/movieMapper.xml
  build/classes/mapper/userMapper.xml
  src/main/java/admin/service/AdminLogOutService.java
  src/main/java/admin/service/AdminSignInDBService.java
  src/main/java/admin/service/AdminSignInService.java
  src/main/java/user/service/UserLogOutService.java
  src/main/java/user/service/UserSignInDBService.java
  src/main/java/user/service/UserSignInService.java
  src/main/java/user/service/UserSignUpDBService.java
  src/main/java/user/service/UserSignUpService.java
  src/main/webapp/admin/adminSignIn.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/js/userSignUp.js
  src/main/webapp/user/userSignIn.jsp
  src/main/webapp/user/userSignUp.jsp
Labels: Client

#37 영화 삭제 구현
  build/classes/mapper/movieMapper.xml
  src/main/java/com/control/ControlServlet.java
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/dao/MovieDAO.java
  src/main/java/movie/service/MovieDeleteDBService.java
  src/main/java/movie/service/MovieViewService.java
  src/main/webapp/WEB-INF/command.properties
  src/main/webapp/admin/movieList.jsp
  src/main/webapp/admin/movieView.jsp
  src/main/webapp/admin/movieWrite.jsp
  src/main/webapp/js/movieView.js
Labels: Server

#38 Dev tw
  build/classes/mapper/userMapper.xml
  src/main/java/com/control/ControlServlet.java
  src/main/java/mapper/userMapper.xml
  src/main/java/user/dao/UserDAO.java
  src/main/java/user/service/UserEditDBService.java
  src/main/java/user/service/UserPwdCheckService.java
  src/main/java/user/service/UserWithdrawDBService.java
  src/main/java/user/service/UserWithdrawService.java
  src/main/webapp/WEB-INF/command.properties
  src/main/webapp/js/userEdit.js
  src/main/webapp/js/userWithdraw.js
  src/main/webapp/user/userEdit.jsp
  src/main/webapp/user/userWithdraw.jsp
Labels: bug

#39 영화 선택 삭제 구현
  build/classes/mapper/movieMapper.xml
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/dao/MovieDAO.java
  src/main/java/movie/service/MovieDeleteDBService.java
  src/main/webapp/admin/movieList.jsp
  src/main/webapp/admin/movieView.jsp
  src/main/webapp/js/movieList.js
  src/main/webapp/js/movieView.js
Labels: Server

#46 로그인 회원가입 css 로직 변경 및 기타 에러 해결
  src/main/webapp/admin/adminSignIn.jsp
  src/main/webapp/css/adminSignIn.css
  src/main/webapp/css/userSignIn.css
  src/main/webapp/css/userSignUp.css
  src/main/webapp/js/adminSignIn.js
  src/main/webapp/js/userSignIn.js
  src/main/webapp/js/userSignUp.js
  src/main/webapp/user/userSignIn.jsp
  src/main/webapp/user/userSignUp.jsp
Labels: bug, Client

#47 로그인 유효성검사 및 오류 수정
  src/main/java/user/service/UserSignInDBService.java
  src/main/webapp/css/userSignIn.css
  src/main/webapp/js/userSignIn.js
  src/main/webapp/user/userSignIn.jsp
Labels: bug, Client

#48 회원가입 오류 수정
  build/classes/.gitignore
  src/main/webapp/js/userSignUp.js
Labels: bug

#53 게시판 검색 기능 구현 토스 준비
  build/classes/.gitignore
  build/classes/mapper/movieMapper.xml
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/dao/MovieDAO.java
  src/main/java/movie/service/MovieDeleteDBService.java
  src/main/java/movie/service/MovieSearchDBService.java
  src/main/java/movie/service/MovieWriteDBService.java
  src/main/webapp/WEB-INF/lib/cos-05Nov2002.jar
  src/main/webapp/admin/movieList.jsp
  src/main/webapp/admin/movieView.jsp
  src/main/webapp/admin/movieWrite.jsp
  src/main/webapp/common/adminMenu.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/css/movieView.css
  src/main/webapp/css/movieWrite.css
  src/main/webapp/js/movieList.js
  src/main/webapp/js/movieView.js
  src/main/webapp/js/movieWrite.js
Labels: bug, documentation

#56 영화 등록 구현
  build/classes/.gitignore
  build/classes/mapper/movieMapper.xml
  src/main/java/main/dao/IndexDAO.java
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/dao/MovieDAO.java
  src/main/java/movie/service/MovieWriteDBService.java
  src/main/webapp/admin/movieWrite.jsp
  src/main/webapp/js/movieWrite.js
Labels: bug, Server

#62 리뷰 페이징 처리
  build/classes/mapper/indexMapper.xml
  build/classes/mapper/reviewMapper.xml
  src/main/java/mapper/indexMapper.xml
  src/main/java/mapper/reviewMapper.xml
  src/main/java/movie/service/MovieListService.java
  src/main/java/review/bean/ReviewPaging.java
  src/main/java/review/dao/ReviewDAO.java
  src/main/java/review/service/ReviewViewService.java
  src/main/webapp/css/reviewView.css
  src/main/webapp/index.jsp
  src/main/webapp/js/reviewView.js
  src/main/webapp/review/reviewView.jsp
Labels: Client, Server

#64 MovieWriteDBService.java mcode, pg 받아오는 코드 제거
  src/main/java/movie/service/MovieWriteDBService.java
Labels: Server

#65 로그인 ui 조정
  src/main/webapp/css/adminSignIn.css
  src/main/webapp/css/userSignIn.css
  src/main/webapp/css/userSignUp.css
  src/main/webapp/user/userSignUp.jsp
Labels: bug

#67 검색 기능, 검색 페이지 처리 구현
  build/classes/mapper/movieMapper.xml
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/bean/MoviePaging.java
  src/main/java/movie/dao/MovieDAO.java
  src/main/java/movie/service/MovieSelectDBService.java
  src/main/webapp/WEB-INF/command.properties
  src/main/webapp/admin/movieList.jsp
  src/main/webapp/css/movieEdit.css
  src/main/webapp/css/movieList.css
  src/main/webapp/css/movieWrite.css
  src/main/webapp/js/movieList.js
Labels: Server

#69 index.jsp 검색 기능 구현, css 조정
  build/classes/mapper/movieMapper.xml
  src/main/java/com/control/ControlServlet.java
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/dao/MovieDAO.java
  src/main/java/movie/service/MovieSearchDBService.java
  src/main/webapp/WEB-INF/command.properties
  src/main/webapp/admin/movieList.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/css/reviewView.css
  src/main/webapp/index.jsp
  src/main/webapp/js/index.js
  src/main/webapp/review/reviewView.jsp
Labels: Client, Server

#70 관리자 로그인 css 조정
  src/main/webapp/admin/adminSignIn.jsp
  src/main/webapp/css/adminSignIn.css
Labels: Client

#72 회원 탈퇴 코드 복붙
  build/classes/mapper/userMapper.xml
  src/main/java/mapper/userMapper.xml
  src/main/java/user/dao/UserDAO.java
  src/main/java/user/service/UserWithdrawDBService.java
  src/main/webapp/css/userWithdraw.css
  src/main/webapp/js/userWithdraw.js
  src/main/webapp/user/userWithdraw.jsp
Labels: bug, Client

#74 Dev tw
  .classpath
  build/classes/.gitignore
  build/classes/mapper/movieMapper.xml
  src/main/java/mapper/movieMapper.xml
  src/main/java/movie/service/MovieSearchDBService.java
  src/main/java/user/dao/UserDAO.java
  src/main/java/user/service/UserPwdCheckService.java
  src/main/webapp/css/movieList.css
  src/main/webapp/js/userEdit.js
  src/main/webapp/js/userWithdraw.js
Labels: bug

#75 index.jsp 영화 포스터 크기 조정
  build/classes/.gitignore
  src/main/webapp/index.jsp
  src/main/webapp/js/index.js
  src/main/webapp/storage/temp.txt
Labels: Client

#76 ReadMe 사진 수정
  src/main/java/user/service/UserWithdrawDBService.java
  src/main/resources/screenshot/FilmNoteERD.png
  src/main/resources/screenshot/review_tb.png
Labels: documentation
